module.exports = [
  {
    ignores: ['node_modules/**', 'coverage/**'],
  },
  {
    files: ['**/*.js'],
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: 'commonjs',
      globals: {
        Buffer: 'readonly',
        console: 'readonly',
        process: 'readonly',
        require: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        exports: 'writable',
        global: 'readonly',
        module: 'writable',
        setImmediate: 'readonly',
        setInterval: 'readonly',
        setTimeout: 'readonly',
        clearImmediate: 'readonly',
        clearInterval: 'readonly',
        clearTimeout: 'readonly',
        URL: 'readonly',
      },
    },
    rules: {
      'no-console': 'off',
      'no-eval': 'error',
      'no-extend-native': 'error',
      'no-global-assign': 'error',
      'no-implied-eval': 'error',
      'no-new-func': 'error',
      'no-octal': 'error',
      'no-proto': 'error',
      'no-redeclare': 'error',
      'no-script-url': 'error',
      'no-self-assign': 'error',
      'no-undef': 'error',
      'no-unreachable': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'no-process-exit': 'off',
      'no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      'use-isnan': 'error',
      'valid-typeof': 'error',
    },
  },
];
